### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by faxm0dem** [hackup/Pi1541io#4]
Hi,

I just built my rev5 board and have a few questions, which are not necessarily all related to the io board.
Keep in mind I haven't hooked it to my C64 yet.

1. What cable should I use ? A straight DIN cable ?
2. My LCD displays the logo after power on, then nothing. On HDMI I just get this:
![2023-02-18-170426_800x550_scrot](https://user-images.githubusercontent.com/112638/219875927-32f05b6b-c286-4ad7-9c32-df1af4e787b1.png)
3. The buzzer doesn't make any sound
4. The reset button does nothing at all

**Comment by hackup** [comment]
1. Use the same IEC cable that you would use to connect an original 1541 to the C64. That is indeed one with a 6-pin DIN-Connector on each end, all lines connected 1:1.
2. Have you copied the 1541 ROM image onto the SD card and named it properly as described on Steve's project page?
3. The buzzer should sound when the emulated drive is moving it's imaginary read/write head. You didn't get that far yet, if I understand correctly.
4. The reset button will reset the emulated 1541 drive once it is running.

I hope this is any help to you. Myself, I don't know the latest firmware versions of the Pi1541 project and cannot support those.

**Comment by faxm0dem** [comment]
Thanks for your help !
2. Yes
4. But there is nothing visible on the LCD or hdmi when pushing the reset button ?

I managed to get further by using `IgnoreReset = 1` in `options.txt` as suggested on a video I found on youtube.
Now the LCD displays the list of files in the `1541` folder, and the HDMI too.
However, neither the keys on a USB keyboard or the buttons seem to do anything.

**Comment by hackup** [comment]
If you changed directories or mounted a d64 image and press the reset button, both displays should return to showing what they displayed initially. Since you can't do this yet, I guess it is normal that the button doesn't seem to do anything. Also, I think that "IgnoreReset=1" will make the Pi1541 ignore resets...

I thought your issues might be caused by you Pi1541 not being connected to the IEC bus yet or by the 1.24 firmware version. So, I just downloaded and installed the latest kernel.img (I still was on 1.21 before), hooked up power, HDMI, and an USB keyboard to the Pi. Both the keyboard and the on board buttons are working in this setup.

I'll attach my own [options.txt](https://github.com/hackup/Pi1541io/files/10776669/options.txt) file here. It is based on an early version of the firmware so there will be parameters missing and relying on default values. But it is working for me with kernel.img 1.24 and might help you. Don't forget though, that you might need to change parameters like LCDName, SplitIECLines, InvertIECInputs, etc. to match your setup.

**Comment by faxm0dem** [comment]
Thanks! I'll try your options asap

**Comment by faxm0dem** [comment]
Hi, I eventually received the correct DIN connectors and soldered them to the board.
I also tried your `options.txt` and many other settings to no avail.

However, I just realised I didn't solder J5-J8 which config should I use (`_IN` or `_BD`) ?

**Comment by hackup** [comment]
Please see the description in my [blog post](https://www.hackup.net/2018/06/pi1541io-revision-2/) on how to configure J5-J8. Also, there is relevant information on the other jumpers to be found in the follow-up posts.

**Comment by faxm0dem** [comment]
Thanks a bunch ! I did that and now it works !
Maybe I can thank you by adding something to the README : if you have this symptom, check J5-J8
